#!/bin/bash
echo "https://t.me/joinchat/RpHwwhjVarVDEL0BCHIk7w"
echo
echo " ENTER THE KEY : "
trap CODE INT
MQCPTLMGSPGMTTPSMCPNGKLPIMTBR12HYG() {
clear
echo  "Loading."
sleep 1
clear
echo "Loading.."
sleep 1
clear
echo "Loading..."
sleep 1
clear
echo "Loading."
sleep 1
clear
echo "Loading.."
sleep 1
clear
echo "Loading..."
sleep 1
clear
echo ""
echo "DONE " | lolcat
sleep 1
bash instacracker.sh
}
